INSERT INTO categories(name,url) VALUES ('AUTOINMUNIDAD','https://drive.google.com/uc?export=view&id=1KuZ_Dcx2scKNWjEypPi2TvHjhGvLqJjo');
INSERT INTO categories(name,url) VALUES ('BIOLOGÍA MOLECULAR','https://drive.google.com/uc?export=view&id=1tJKt4RiUzdVqIpKBxxOg3_R0Z3fV4JzT');
INSERT INTO categories(name,url) VALUES ('COAGULACIÓN','https://drive.google.com/uc?export=view&id=1U6yzUSgKjBYJkUxbRuImvMaKNay67QMo');
INSERT INTO categories(name,url) VALUES ('COPROANÁLISIS','https://drive.google.com/uc?export=view&id=1P9SzIOGgK4dAAFfP9w1BULStj9IGHzkl');
INSERT INTO categories(name,url) VALUES ('ENFERMEDAD RESPIRATORIA AGUDA','https://drive.google.com/uc?export=view&id=15rKts7toVBaj5U-7EMbwQXVsyMZVUaD4');
INSERT INTO categories(name,url) VALUES ('HEMATOLOGÍA','https://drive.google.com/uc?export=view&id=1AT_Nsur3PFBcDiPGivXs0CMeKf7HrvYs');
INSERT INTO categories(name,url) VALUES ('HORMONAL','https://drive.google.com/uc?export=view&id=1zO4jPVEJRAMsO1jfejmEJpIra5FQORD0');
INSERT INTO categories(name,url) VALUES ('INMUNOLOGÍA','https://drive.google.com/uc?export=view&id=178fzqrVu6BD9I-E0cPu8J8rTxOaeBLXH');
INSERT INTO categories(name,url) VALUES ('MICROBIOLOGÍA','https://drive.google.com/uc?export=view&id=1OkcEdU_mRLDu-Q1jNcS2ukm5tUwieiXa');
INSERT INTO categories(name,url) VALUES ('QUÍMICA CLÍNICA','https://drive.google.com/uc?export=view&id=1Xr-vXBA8mDGG6ZAYVwnZyJXl6llGogFc');
INSERT INTO categories(name,url) VALUES ('SEROLOGÍA','https://drive.google.com/uc?export=view&id=1gZchIQ2uZxekexZQYULmv-6rOCpc3jCV');
INSERT INTO categories(name,url) VALUES ('UROANÁLISIS','https://drive.google.com/uc?export=view&id=1WKZHRYH08mmq4lJ6xl8zH_YOpPRKkknO');
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI BETA 2 GLICOPROTEÍNA IGG E IGM','Ayuno de 8 horas.','Entrega de resultados los días lunes, miércoles y viernes. La entrega de resultado dependerá del día en que fue tomada la muestra.',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI CARDIOLIPINAS IGG E IGM','Ayuno de 8 horas.','Entrega de resultados los días lunes, miércoles y viernes. La entrega de resultado dependerá del día en que fue tomada la muestra.',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTICOAGULANTE LÚPICO','Ayuno de 8 horas.','Mismo día',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL ENA','Ayuno de 8 horas.','Entrega de resultados los días lunes, miércoles y viernes. La entrega de resultado dependerá del día en que fue tomada la muestra.',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL VASCULITIS','Ayuno de 8 horas.','Entrega de resultados los días lunes, miércoles y viernes. La entrega de resultado dependerá del día en que fue tomada la muestra.',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COMPLEMENTO C3 Y C4','Ayuno de 8 horas.','Mismo día',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTIESTREPTOLISINAS (ASO)','Ayuno de 8 horas.','Mismo día',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COOMBS DIRECTO','No requiere ayuno','Mismo día',true,1);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PCR VIRUS PAPILOMA HUMANO (VPH) 14 GENOTIPOS','Mujeres: 5 días después del sangrado visible. Hombres: 2 hrs. sin haber orinado','Mismo día',true,2);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('DIMERO D','Ayuno de 8 horas.','Mismo día',true,3);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('TIEMPOS DE COAGULACION','Ayuno de 8 horas.','Mismo día',true,3);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COPROPARASITOSCÓPICO SERIADO (3 MUESTRAS)','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección, por 3 días consecutivos.','El día de entrega de la última muestra.',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AMOEBA EN FRESCO','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CITOLOGÍA EN MOCO FECAL','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COPROLÓGICO','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COPROPARASITOSCÓPICO (CPS)','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('SANGRE OCULTA EN HECES (GUAYACO)','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AG DE GIARDIA/ CRYPTOSPORIDIUM EN HECES','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTÍGENO DE HELICOBACTER PYLORI EN HECES','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','Mismo día',true,4);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AG VIRUS SINCITIAL RESPIRATORIO','No haber usado algún tipo de aerosol nasal.','Mismo día',true,5);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTÍGENO DE SARS COV.2','No haber usado algún tipo de aerosol nasal.','Mismo día',true,5);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PRUEBA RÁPIDA DE INFLUENZA','No haber usado algún tipo de aerosol nasal.','Mismo día',true,5);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANDROSTENEDIONA','Ayuno de 10 a 12 horas','2 días hábiles',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('DEHIDROEPIANDROSTERONA TOTAL (DHEA-S)','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ESTRADIOL','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('HORMONA ESTIMULANTE DE LA TIROIDES (TSH)','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('HORMONA ESTIMULANTE DE LOS FOLÍCULOS (FSH)','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('HORMONA LUTEINIZANTE (LH)','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('INSULINA SERICA','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL TIROIDEO','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PROGESTERONA','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PROLACTINA','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('TESTOSTERONA LIBRE','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('TESTOSTERONA TOTAL','Ayuno de 8 horas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL HORMONAL GINECOLÓGICO','Ayuno de 8 horas. Sujeto a indicaciones médicas.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('EOSINÓFILOS EN MOCO NASAL','No haber usado algún tipo de aerosol nasal.','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('BIOMETRÍA HEMÁTICA','No requiere ayuno','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('RETICULOCITOS EN SANGRE PERIFERICA','No requiere ayuno','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('SUBPOBLACIÓN DE LINFOCITOS (CD3, CD4 Y CD8)','No requiere ayuno','Mismo día',true,6);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI CITOMEGALOVIRUS IGG E IGM','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI HEPATITIS A IGG E IGM','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI HEPATITIS C TOTALES','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI TOXOPLASMA IGG E IGM','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('FERRITINA','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('FRACCION BETA DE LA GONADOTROPINA CORIONICA HUMANA','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('INMUNOGLOBULINA A (IGA)','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('INMUNOGLOBULINA E (IGE)','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('INMUNOGLOBULINA G (IGG)','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('INMUNOGLOBULINA M (IGM)','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL DE AC ANTI VIRUS EPSTEIN BARR','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL DE ALERGENOS INHALATORIOS','Ayuno de 8 horas.','2 días hábiles',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL DE HIERRO COMPLETO (FERRITINA Y TRANSFERRINA)','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL DE INMUNOGLOBULINAS (IGA/IGG/IGM)','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL TORCH IGG','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL TORCH IGG E IGM','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL TORCH IGM','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('VITAMINA D','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('WESTERN BLOT VIH (PRUEBA CONFIRMATORIA)','Ayuno de 8 horas.','5 días hábiles',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('HIERRO SÉRICO','Ayuno de 8 horas.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PSA TOTAL','Ayuno de 8 horas. No haber realizado ejercicio en las últimas 24 hrs. Abstinencia sexual de 3 a 5 días.','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AC ANTI VIH 1 Y 2','No requiere ayuno','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COOMBS INDIRECTO','No requiere ayuno','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PROCALCITONINA','No requiere ayuno','Mismo día',true,7);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTIGENO CARCINOEMBRIONARIO','Ayuno de 8 horas.','Mismo día',true,8);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CULTIVO DE EXUDADO VAGINAL','Abstinecia sexual de 3 a 5 días. No presentar sangrado.','4 días hábiles',true,9);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('BAAR (1 MUESTRA)','Expectoración (previo a la ingesta de alimentos se requiere esputo no saliva. Orina (micción completa), recolectar desde el primer chorro.','1 día hábil',true,9);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('BAAR SERIADO (3 MUESTRAS)','Expectoración (previo a la ingesta de alimentos se requiere esputo no saliva. Orina (micción completa), recolectar desde el primer chorro. Por 3 días consecutivos.','1 día hábil después de entregar la última muestra.',true,9);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COPROCULTIVO','Muestra de heces fecales en vaso estéril con no más de 3 horas de recolección.','4 días hábiles',true,9);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('UROCULTIVO','Muestra de primera orina del día (chorro medio) previo aseo.','4 días hábiles',true,9);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('EXUDADO FARÍNGEO','No haber usado algún tipo de aerosol nasal.','4 días hábiles',true,9);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('COLESTEROL TOTAL','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('GLUCOSA, COLESTEROL Y TRIGLICERIDOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL DE LIPIDOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUÍMICA SANGUÍNEA DE 18 ELEMENTOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUÍMICA SANGUÍNEA DE 24','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUÍMICA SANGUÍNEA DE 27 ELEMENTOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUÍMICA SANGUÍNEA DE 30 ELEMENTOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUIMICA SANGUÍNEA DE 12 ELEMENTOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUIMICA SANGUINEA 45 ELEMENTOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUIMICA SANGUINEA DE 6 ELEMENTOS','Ayuno de 10 a 12 horas','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ALT (TGP)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('AST(TGO)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('BILIRRUBINAS (TOTAL, DIRECTA E INDIRECTA)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CALCIO SÉRICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CLORO SÉRICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CPK Y CK-MB','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CREATINFOSFOQUINASA (CPK)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CREATINFOSFOQUINASA FRACCION MB (CK-MB)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('CURVA DE TOLERANCIA A LA GLUCOSA 2 HORAS','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ELECTROLITOS DE 6','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ELECTROLITOS SÉRICOS (SODIO, POTASIO Y CLORO)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('FOSFORO SÉRICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('GLUCOSA SÉRICA','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('LACTATO DESHIDROGENASA (LDH)','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('MAGNESIO SÉRICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('POTASIO SÉRICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PROTEÍNAS TOTALES','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PRUEBAS DE FUNCIONAMIENTO HEPÁTICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUIMICA SANGUÍNEA DE 3 ELEMENTOS','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('QUIMICA SANGUÍNEA DE 4 ELEMENTOS','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('SODIO SÉRICO','Ayuno de 8 horas.','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('HEMOGLOBINA GLICOSILADA','No requiere ayuno','Mismo día',true,10);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTIGENO DE SUPERFICIE HEPATITIS B','Ayuno de 8 horas.','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('DENGUE DUO AG NS1 IGG E IGM','Ayuno de 8 horas.','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('FACTOR REUMATOIDE','Ayuno de 8 horas.','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PERFIL REUMÁTICO','Ayuno de 8 horas.','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PROTEÍNA C REACTIVA','Ayuno de 8 horas.','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('GRUPO SANGUÍNEO Y FACTOR RH','No requiere ayuno','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('PRUEBA DE EMBARAZO CUALITATIVA','No requiere ayuno','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('REACCIONES FEBRILES','No requiere ayuno','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('REACCIONES LUÉTICAS V.D.R.L. (Sífilis)','No requiere ayuno','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('VELOCIDAD DE SEDIMENTACION GLOBULAR','No requiere ayuno','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('ANTIDOPING 5 ELEMENTOS','Orina espontánea, la toma de muestra requiere vigilancia del químico.','Mismo día',true,11);
INSERT INTO studies(name,indications,wait_time,active,fk_category_id) VALUES ('EXAMEN GENERAL DE ORINA','Muestra de primera orina del día (chorro medio) previo aseo.','Mismo día',true,12);
INSERT INTO roles(role_name) VALUES ('admin');
INSERT INTO roles(role_name) VALUES ('user');
INSERT INTO customers(name,lastname,lastname2,birthdate,email,password,phonenumber,sex,active,fk_role_id) VALUES ('admin','admin','admin','2000-01-01','admin@example.com','P@ssw0rd123',1234567890,'male',true,1);
INSERT INTO customers(name,lastname,lastname2,birthdate,email,password,phonenumber,sex,active,fk_role_id) VALUES ('Luisa','Eysele','Gamboa','2000-01-01','eysele.luisa@gmail.com','123',9992757306,'female',true,1);
INSERT INTO customers(name,lastname,lastname2,birthdate,email,password,phonenumber,sex,active,fk_role_id) VALUES ('John','Smith','Brooks','1987-12-05','john.smith@example.com','P@ssw0rd123',1234567890,'male',true,2);
INSERT INTO customers(name,lastname,lastname2,birthdate,email,password,phonenumber,sex,active,fk_role_id) VALUES ('Emily','Johnson','Cruise','1992-03-23','emily.johnson@example.com','SecretPass123',2345678901,'female',true,2);
INSERT INTO customers(name,lastname,lastname2,birthdate,email,password,phonenumber,sex,active,fk_role_id) VALUES ('Michael','Davis',NULL,'1985-09-18','michael.davis@example.com','StrongPwd456',3456789012,'male',true,2);
INSERT INTO customers(name,lastname,lastname2,birthdate,email,password,phonenumber,sex,active,fk_role_id) VALUES ('Sarah','Williams',NULL,'1990-02-12','sarah.williams@example.com','SecurePass789',4567890123,'female',true,2);